from django.urls import path
from .views import (
    home_view, 
    store_create_view, store_list_view, store_update_view, store_detail_view, store_delete_view,
    distributor_create_view, distributor_delete_view, distributor_update_view, distributor_list_view, distributor_detail_view,
    category_create_view, category_update_view, category_list_view, category_delete_view, category_detail_view,
    size_create_view, size_update_view, size_list_view, size_delete_view, size_detail_view,
    inventory_item_create_view, inventory_item_delete_view, inventory_item_detail_view, inventory_item_list_view, inventory_item_update_view,
    item_create_view, item_detail_view, item_delete_view, item_update_view,
    inventory_item_upc_create_view, inventory_item_upc_delete_view, inventory_item_upc_detail_view, inventory_item_upc_update_view,
    store_transfer_view,
)

app_name = 'storetransfer'
urlpatterns = [
    path('', home_view, name='home'),
    path('store/', store_list_view, name='store-list'),
    path('store/create/', store_create_view, name='store-create'),
    path('store/<int:id>/', store_detail_view, name='store-detail'),
    path('store/<int:id>/update/', store_update_view, name='store-update'),
    path('store/<int:id>/delete/', store_delete_view, name='store-delete'),
    path('store/<int:store_id>/create/', item_create_view, name='item-create'),
    path('store/<int:store_id>/<int:id>/', item_detail_view, name='item-detail'),
    path('store/<int:store_id>/<int:id>/update/', item_update_view, name='item-update'),
    path('store/<int:store_id>/<int:id>/delete/', item_delete_view, name='item-delete'),
    path('distributor/', distributor_list_view, name='distributor-list'),
    path('distributor/create/', distributor_create_view, name='distributor-create'),
    path('distributor/<int:id>/', distributor_detail_view, name='distributor-detail'),
    path('distributor/<int:id>/update/', distributor_update_view, name='distributor-update'),
    path('distributor/<int:id>/delete/', distributor_delete_view, name='distributor-delete'),
    path('category/', category_list_view, name='category-list'),
    path('category/create/', category_create_view, name='category-create'),
    path('category/<int:id>/', category_detail_view, name='category-detail'),
    path('category/<int:id>/update/', category_update_view, name='category-update'),
    path('category/<int:id>/delete/', category_delete_view, name='category-delete'),
    path('size/', size_list_view, name='size-list'),
    path('size/create/', size_create_view, name='size-create'),
    path('size/<int:id>/', size_detail_view, name='size-detail'),
    path('size/<int:id>/update/', size_update_view, name='size-update'),
    path('size/<int:id>/delete/', size_delete_view, name='size-delete'),
    path('inventory_item/', inventory_item_list_view, name='inventory-item-list'),
    path('inventory_item/create/', inventory_item_create_view, name='inventory-item-create'),
    path('inventory_item/<int:id>/', inventory_item_detail_view, name='inventory-item-detail'),
    path('inventory_item/<int:id>/update/', inventory_item_update_view, name='inventory-item-update'),
    path('inventory_item/<int:id>/delete/', inventory_item_delete_view, name='inventory-item-delete'),
    path('inventory_item/<int:inventory_item_id>/create/', inventory_item_upc_create_view, name='inventory-item-upc-create'),
    path('inventory_item/<int:inventory_item_id>/<int:id>/', inventory_item_upc_detail_view, name='inventory-item-upc-detail'),
    path('inventory_item/<int:inventory_item_id>/<int:id>/update/', inventory_item_upc_update_view, name='inventory-item-upc-update'),
    path('inventory_item/<int:inventory_item_id>/<int:id>/delete/', inventory_item_upc_delete_view, name='inventory-item-upc-delete'),
    path('store_transfer/', store_transfer_view, name='store-transfer'),
]