# Generated by Django 2.2.6 on 2019-11-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=100)),
                ('distributor_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sku', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('item_case_cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('item_split_bottle_cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('item_retail_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('item_MPQ', models.IntegerField()),
                ('item_on_hand_count', models.IntegerField()),
                ('item_error_value', models.BooleanField(default=False)),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storetransfer.Category')),
                ('item_distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storetransfer.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UPCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_type_name', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storetransfer.Item')),
            ],
        ),
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=20)),
                ('upc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storetransfer.UPCType')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storetransfer.Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storetransfer.Store'),
        ),
    ]
