# Generated by Django 2.2.6 on 2019-11-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0002_auto_20191119_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storetransfer.Store'),
        ),
    ]
