# Generated by Django 2.2.6 on 2019-11-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0003_auto_20191125_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item_sku_sku', models.CharField(max_length=20)),
                ('inventory_item_sku_name', models.CharField(max_length=100)),
                ('inventory_item_sku_case_cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('inventory_item_sku_split_bottle_cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('inventory_item_sku_MPQ', models.IntegerField()),
                ('inventory_item_sku_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storetransfer.Category')),
                ('inventory_item_sku_distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storetransfer.Distributor')),
                ('inventory_item_sku_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storetransfer.Size')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemUPCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item_upc_type_name', models.CharField(max_length=100)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storetransfer.InventoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemUPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_item_upc', models.CharField(max_length=20)),
                ('inventory_item_upc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storetransfer.InventoryItemUPCType')),
            ],
        ),
    ]
