# Generated by Django 2.2.6 on 2019-11-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0005_auto_20191126_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upc',
            name='upc_type',
        ),
        migrations.RemoveField(
            model_name='upctype',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryitemupc',
            name='inventory_item_upc_type',
        ),
        migrations.AddField(
            model_name='inventoryitemupc',
            name='inventory_item',
            field=models.ForeignKey(default=546788, on_delete=django.db.models.deletion.CASCADE, to='storetransfer.InventoryItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitemupc',
            name='inventory_item_upc_type_name',
            field=models.CharField(default=5467832, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_upc',
            field=models.CharField(default=2434, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventoryItemUPCType',
        ),
        migrations.DeleteModel(
            name='UPC',
        ),
        migrations.DeleteModel(
            name='UPCType',
        ),
    ]
