# Generated by Django 2.2.7 on 2019-12-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0006_auto_20191127_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='distributor_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
