# Generated by Django 2.2.6 on 2019-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0007_auto_20191206_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_item_upc',
            field=models.CharField(default=85423670, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InventoryItemUPC',
        ),
    ]
