# Generated by Django 2.2.6 on 2019-12-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0008_auto_20191212_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_sku',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_upc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_sku',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_upc',
            field=models.IntegerField(),
        ),
    ]
