# Generated by Django 2.2.6 on 2019-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storetransfer', '0009_auto_20191212_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_sku',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_item_upc',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_sku',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_upc',
            field=models.BigIntegerField(),
        ),
    ]
